name: spotify
description: "Listen music with spotify."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: 8.1.6

  cupertino_icons: ^1.0.8
  flutter_svg:
  hydrated_bloc:
  path_provider:
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

# dart run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"

# dart run flutter_native_splash:create
flutter_native_splash:
  android: true
  color: "#ffffff"
  color_dark: "#000000"
  android_12:
    image: "assets/images/icon-framed.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/icon-framed.png"
    icon_background_color_dark: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # build_runner:
  # freezed: 2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
